repos:
 - repo: https://github.com/keep-network/pre-commit-golang.git
   rev: 4cc73f21101f9da1208719b02bbbe0a4c491497e
   hooks:
    - id: go-imports
    - id: go-vet
    - id: go-lint
 - repo: https://github.com/keep-network/pre-commit-hooks.git
   rev: 63e729f
   hooks:
    - id: check-added-large-files
 - repo: local
   hooks:
    - id: solium
      name: Solidity linter
      language: node
      entry: solium
      files: '\.sol$'
      args:
      - --dir=solidity/contracts/
      - --config=solidity/.soliumrc.json
      additional_dependencies:
      - ethlint@1.2.3