# This is a TOML configuration file.

# Connection details of ethereum blockchain.
[ethereum]
  URL = "Set by Kube"
  URLRPC = "Set by Kube"

[ethereum.account]
  KeyFile = "Set by Kube"

# Addresses of contracts deployed on ethereum blockchain.
[ethereum.ContractAddresses]
  BondedECDSAKeepFactory = "Set by Kube"

# Addresses of applications approved by the operator.
[SanctionedApplications]
  Addresses = ["Set by Kube"]

[LibP2P]
  Peers = []
  Port = ""
  AnnouncedAddresses = []

[Storage]
    DataDir = "Set by Kube"
