---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keep-tecdsa
  namespace: default
  labels:
    keel.sh/policy: all
    app: keep
    type: tecdsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keep
      type: tecdsa
  serviceName: keep-tecdsa
  volumeClaimTemplates:
    - metadata:
        name: keep-tecdsa-data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 512Mi
  template:
    metadata:
      labels:
        app: keep
        type: tecdsa
    spec:
      containers:
        - name: keep-tecdsa
          image: gcr.io/keep-dev-fe24/keep-tecdsa
          resources:
            limits:
              cpu: "3"
            requests:
              cpu: "2"
          env:
            - name: KEEP_ETHEREUM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eth-account-passphrase
                  key: account-passphrase
            - name: LOG_LEVEL
              value: "keep*=debug tss-lib=warning"
          volumeMounts:
            - name: keep-tecdsa-config
              mountPath: /mnt/keep-tecdsa/config
            - name: keep-tecdsa-data
              mountPath: /mnt/keep-tecdsa/data
            - name: eth-account-keyfile
              mountPath: /mnt/keep-tecdsa/eth
          command:
            [
              "keep-tecdsa",
              "-config",
              "/mnt/keep-tecdsa/config/keep-tecdsa-config.toml",
              "start",
            ]
      volumes:
        - name: eth-account-keyfile
          configMap:
            name: keep-tecdsa
        - name: keep-tecdsa-config
          persistentVolumeClaim:
            claimName: keep-tecdsa-config
        - name: keep-tecdsa-data
          persistentVolumeClaim:
            claimName: keep-tecdsa-data
      initContainers:
        - name: initcontainer-provision-keep-tecdsa
          image: gcr.io/keep-dev-fe24/initcontainer-provision-keep-tecdsa
          env:
            - name: ETH_RPC_URL
              valueFrom:
                configMapKeyRef:
                  name: eth-network-internal
                  key: rpc-url
            - name: ETH_WS_URL
              valueFrom:
                configMapKeyRef:
                  name: eth-network-internal
                  key: ws-url
            - name: ETH_NETWORK_ID
              valueFrom:
                configMapKeyRef:
                  name: eth-network-internal
                  key: network-id
            - name: CONTRACT_OWNER_ETH_ACCOUNT_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eth-network-internal
                  key: contract-owner-eth-account-address
            - name: CONTRACT_OWNER_ETH_ACCOUNT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: eth-network-internal
                  key: contract-owner-eth-account-private-key
            - name: TBTC_SYSTEM_ADDRESS
              value: "0xcA9b18ebeE7CE5CA481bE3B3C0bC8209d28C807A"
            - name: KEEP_TECDSA_ETH_KEYFILE_1
              value: /mnt/keep-tecdsa/eth/eth_account_keyfile_1
            - name: KEEP_TECDSA_ETH_KEYFILE_2
              value: /mnt/keep-tecdsa/eth/eth_account_keyfile_2
            - name: KEEP_TECDSA_ETH_KEYFILE_3
              value: /mnt/keep-tecdsa/eth/eth_account_keyfile_3
            - name: KEEP_DATA_DIR
              value: /mnt/keep-tecdsa/data
          volumeMounts:
            - name: keep-tecdsa-config
              mountPath: /mnt/keep-tecdsa/config
            - name: eth-account-keyfile
              mountPath: /mnt/keep-tecdsa/eth
          command: ["node", "/tmp/provision-keep-tecdsa.js"]
      nodeSelector:
        pool-type: keep-tecdsa
      tolerations:
        - key: type
          operator: Equal
          value: tecdsa
          effect: NoSchedule

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keep-tecdsa-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
