version: 2.1

executors:
  docker-node:
    docker:
      - image: circleci/node:11
  docker-git:
    docker:
      - image: docker:18.06.0-ce-git
  docker-thesis-buildpack:
    docker:
      - image: thesisco/docker-buildpack:bionic

orbs:
  gcp-cli: circleci/gcp-cli@1.8.2
  gcp-gcr: circleci/gcp-gcr@0.0.4

jobs:
  setup_github_package_registry:
    executor: docker-node
    steps:
      - checkout
      - run:
          name: Authenticate GitHub Package Registry
          working_directory: ~/project/solidity
          command: echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> .npmrc
      - persist_to_workspace:
          root: solidity
          paths:
            - .npmrc
  lint:
    executor: docker-node
    steps:
      - checkout
      - attach_workspace:
          at: solidity
      - run:
          name: Lint Implementation
          working_directory: ~/project/solidity
          command: |
            set -ex
            npm run lint
  build_and_test_solidity:
    executor: docker-node
    steps:
      - checkout
      - attach_workspace:
          at: solidity
      - run: npm install ganache-cli@6.9.1
      - run:
          name: Running testrpc
          command: |
            cd $(npm bin)
            ./ganache-cli
          background: true
      - run:
          name: Setup solidity
          working_directory: ~/project/solidity
          command: npm install
      - run:
          name: Build solidity contracts
          working_directory: ~/project/solidity
          command: npm run build
      - run:
          name: Run solidity tests
          working_directory: ~/project/solidity
          command: npm run test
  build_client_and_test_go:
    executor: docker-git
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - attach_workspace:
          at: solidity
      - run:
          name: Build Go build environment image
          command: |
            docker build \
              --build-arg GITHUB_TOKEN=$GITHUB_TOKEN\
              --build-arg GOPRIVATE=$GOPRIVATE\
              --tag go-build-env \
              --target gobuild .
      - run:
          name: Run Go tests
          command: |
            docker run \
              --workdir /go/src/github.com/keep-network/keep-ecdsa \
              go-build-env \
              go test ./.../
      - run:
          name: Build keep-ecdsa runtime image
          command: |
            docker build \
              --build-arg GITHUB_TOKEN=$GITHUB_TOKEN \
              --tag keep-ecdsa .
      - run:
          name: Save keep-ecdsa image
          command: |
            mkdir -p /tmp/keep-ecdsa/docker-images
            docker save \
              --output /tmp/keep-ecdsa/docker-images/keep-ecdsa.tar \
              keep-ecdsa
      - persist_to_workspace:
          root: /tmp/keep-ecdsa
          paths:
            - docker-images
  build_initcontainer:
    executor: docker-thesis-buildpack
    steps:
      - attach_workspace:
          at: /tmp/keep-ecdsa
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Set Gcloud Auth for bucket access
          command: |
            echo $GCLOUD_SERVICE_KEY > ~/gcloud-service-key.json
            gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
      - run:
          name: Build keep-ecdsa-initcontainer image
          working_directory: ~/project/infrastructure/kube/templates/keep-ecdsa/initcontainer/provision-keep-ecdsa/
          command: |
            gsutil cp gs://${CONTRACT_DATA_BUCKET}/keep-core/KeepToken.json .
            gsutil cp gs://${CONTRACT_DATA_BUCKET}/keep-core/TokenStaking.json .
            cp /tmp/keep-ecdsa/contracts/BondedECDSAKeepFactory.json .
            cp /tmp/keep-ecdsa/contracts/KeepBonding.json .

            docker build \
              --tag initcontainer-provision-keep-ecdsa .
      - run:
          name: Save keep-ecdsa-initcontainer image
          command: |
            mkdir -p /tmp/keep-ecdsa/docker-images
            docker save \
              --output /tmp/keep-ecdsa/docker-images/initcontainer-provision-keep-ecdsa.tar \
              initcontainer-provision-keep-ecdsa
      - persist_to_workspace:
          root: /tmp/keep-ecdsa
          paths:
            - docker-images
  migrate_contracts:
    executor: docker-thesis-buildpack
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - attach_workspace:
          at: solidity
      - run:
          name: Set Gcloud Auth for bucket access
          command: |
            echo $GCLOUD_SERVICE_KEY > ~/gcloud-service-key.json
            gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
      - run:
          name: Fetch external contracts artifacts
          command: |
            solidity/scripts/circleci-provision-external-contracts.sh
      - run:
          name: Set Gcloud Auth for jumphost SSH
          command: |
            echo $GCLOUD_SERVICE_KEY_JUMPHOST_SSH > ~/gcloud-service-key.json
            gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
      - run:
          name: Migrate Contracts
          command: |
            export BUILD_TAG=$CIRCLE_SHA1
            export TRUFFLE_NETWORK=$TRUFFLE_NETWORK
            mkdir -p /tmp/keep-ecdsa/contracts
            solidity/scripts/circleci-migrate-contracts.sh
      - persist_to_workspace:
          root: /tmp/keep-ecdsa
          paths:
            - contracts
  publish_client:
    executor: gcp-gcr/default
    steps:
      - attach_workspace:
          at: /tmp/keep-ecdsa
      - run:
          name: Load Docker images
          command: |
            docker load -i /tmp/keep-ecdsa/docker-images/keep-ecdsa.tar
            docker load -i /tmp/keep-ecdsa/docker-images/initcontainer-provision-keep-ecdsa.tar
      - run:
          name: Tag Docker images
          command: |
            docker tag keep-ecdsa $GCR_REGISTRY_URL/$GOOGLE_PROJECT_ID/keep-ecdsa
            docker tag initcontainer-provision-keep-ecdsa $GCR_REGISTRY_URL/$GOOGLE_PROJECT_ID/initcontainer-provision-keep-ecdsa
      - gcp-gcr/gcr-auth:
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE_A
          # This param doesn't actually set anything, leaving here as a reminder to check when they fix it.
          gcloud-service-key: GCLOUD_SERVICE_KEY
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          registry-url: $GCR_REGISTRY_URL
          image: keep-ecdsa
          tag: latest
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          registry-url: $GCR_REGISTRY_URL
          image: initcontainer-provision-keep-ecdsa
          tag: latest
  publish_contract_data:
    executor: gcp-cli/default
    steps:
      - attach_workspace:
          at: /tmp/keep-ecdsa
      - gcp-cli/install
      - gcp-cli/initialize:
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE_A
          # This param doesn't actually set anything, leaving here as a reminder to check when they fix it.
          gcloud-service-key: GCLOUD_SERVICE_KEY
      - run:
          name: Upload contract data
          command: |
            cd /tmp/keep-ecdsa/contracts
            gsutil -m cp * gs://${CONTRACT_DATA_BUCKET}/keep-ecdsa

workflows:
  version: 2
  lint:
    jobs:
      - setup_github_package_registry:
          context: github-package-registry
      - lint
  solidity:
    jobs:
      - setup_github_package_registry:
          context: github-package-registry
      - build_and_test_solidity:
          requires:
            - setup_github_package_registry
  build-test-migrate-publish-keep-dev:
    jobs:
      - setup_github_package_registry:
          context: github-package-registry
      - build_client_and_test_go:
          context: github-package-registry
          requires:
            - setup_github_package_registry
      - migrate_contracts:
          filters:
            branches:
              only: master
          context: keep-dev
          requires:
            - build_client_and_test_go
      - build_initcontainer:
          filters:
            branches:
              only: master
          context: keep-dev
          requires:
            - migrate_contracts
      - publish_client:
          filters:
            branches:
              only: master
          context: keep-dev
          requires:
            - build_client_and_test_go
            - build_initcontainer
            - migrate_contracts
      - publish_contract_data:
          filters:
            branches:
              only: master
          context: keep-dev
          requires:
            - migrate_contracts
  build-test-migrate-publish-keep-test:
    jobs:
      - keep_test_approval:
          type: approval
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - setup_github_package_registry:
          context: github-package-registry
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - keep_test_approval
      - build_client_and_test_go:
          context: github-package-registry
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - setup_github_package_registry
      - migrate_contracts:
          context: keep-test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - build_client_and_test_go
      - build_initcontainer:
          context: keep-test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - migrate_contracts
      - publish_client:
          context: keep-test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - build_client_and_test_go
            - build_initcontainer
            - migrate_contracts
      - publish_contract_data:
          context: keep-test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - migrate_contracts
