version: 2.1

executors:
  docker-node:
    docker:
      - image: circleci/node:11
  docker-git:
    docker:
      - image: docker:18.06.0-ce-git
  docker-thesis-buildpack:
    docker:
      - image: thesisco/docker-buildpack:bionic      

orbs:
  gcp-gcr: circleci/gcp-gcr@0.0.4

jobs:
  build_and_test_solidity:
    executor: docker-node
    steps:
        - checkout
        - run: npm install ganache-cli@6.4.2
        - run:
            name: Running testrpc
            command: |
              cd $(npm bin)
              ./ganache-cli
            background: true
        - run: 
            name: Setup solidity
            command: |
              cd solidity
              npm install
        - run: 
            name: Build solidity contracts
            command: |
              cd solidity
              npm run build
        - run: 
            name: Run solidity tests
            command: |
              cd solidity 
              npm run test
  build_client_and_test_go:
    executor: docker-git
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Run Docker build
          command: |
            docker build --build-arg GITHUBTOKEN=$GITHUBTOKEN -t go-build-env --target gobuild .
            docker build --build-arg GITHUBTOKEN=$GITHUBTOKEN -t $GCR_REGISTRY_URL/$GOOGLE_PROJECT_ID/keep-tecdsa .
      - run:
          name: Run Go tests
          command: |
            docker run -w /go/src/github.com/keep-network/keep-tecdsa go-build-env go test ./.../
      - run:
          name: Save keep-tecdsa image
          command: |
            mkdir -p /tmp/images/keep-tecdsa/
            docker save -o /tmp/images/keep-tecdsa/keep-tecdsa.tar $GCR_REGISTRY_URL/$GOOGLE_PROJECT_ID/keep-tecdsa
      - persist_to_workspace:
          root: /tmp/images
          paths:
            - keep-tecdsa
  migrate_contracts:
    executor: docker-thesis-buildpack
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Set Gcloud Auth
          command: |
            echo $GCLOUD_SERVICE_KEY_JUMPHOST_SSH > ~/gcloud-service-key.json
            gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
      - run:
          name: Migrate Contracts
          command: |
            export BUILD_TAG=$CIRCLE_SHA1
            export TRUFFLE_NETWORK=$TRUFFLE_NETWORK
            mkdir -p /tmp/keep-client/contracts
            solidity/scripts/circleci-migrate-contracts.sh
      - persist_to_workspace:
          root: /tmp/keep-client
          paths:
            - contracts            
  publish_client:
    executor: gcp-gcr/default
    steps:
      - attach_workspace:
          at: /tmp/images
      - run:
          name: Load keep-tecdsa image
          command: |
            docker load -i /tmp/images/keep-tecdsa/keep-tecdsa.tar
      - gcp-gcr/gcr-auth:
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE_A
          # This param doesn't actually set anything, leaving here as a reminder to check when they fix it.
          gcloud-service-key: GCLOUD_SERVICE_KEY
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          registry-url: $GCR_REGISTRY_URL
          image: keep-tecdsa
          tag: latest

workflows:
  version: 2
  solidity:
    jobs:
      - build_and_test_solidity
  build-test-migrate-publish:
    jobs:
      - build_client_and_test_go:
          context: keep-dev
      - migrate_contracts:
          context: keep-dev
          requires: 
            - build_client_and_test_go
      - publish_client:
          filters:
            branches:
              only: master
          context: keep-dev
          requires:
            - build_client_and_test_go
            - migrate_contracts
